### ISSUE TITLE
Metadata not updating after adding Show

### ISSUE THREAD

**Issue by Fabaderheld** [bonukai/MediaTracker#158]
As the title states after adding a show, no metadata is added and throws errors in the logs
```
Updating: Dexter (last updated at: 2/16/2022, 6:45:00 AM)
error: insert into "season" ("description", "id", "isSpecialSeason", "numberOfEpisodes", "poster", "releaseDate", "seasonNumber", "title", "tmdbId", "tvShowId") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) returning "id" - null value in column "id" of relation "season" violates not-null constraint
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Updating: Dexter (last updated at: 2/16/2022, 6:45:00 AM)
error: insert into "season" ("description", "id", "isSpecialSeason", "numberOfEpisodes", "poster", "releaseDate", "seasonNumber", "title", "tmdbId", "tvShowId") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) returning "id" - null value in column "id" of relation "season" violates not-null constraint
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Updating: Dexter (last updated at: 2/16/2022, 6:45:00 AM)
error: insert into "season" ("description", "id", "isSpecialSeason", "numberOfEpisodes", "poster", "releaseDate", "seasonNumber", "title", "tmdbId", "tvShowId") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) returning "id" - null value in column "id" of relation "season" violates not-null constraint
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Updating: Dexter (last updated at: 2/16/2022, 6:45:00 AM)
error: insert into "season" ("description", "id", "isSpecialSeason", "numberOfEpisodes", "poster", "releaseDate", "seasonNumber", "title", "tmdbId", "tvShowId") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) returning "id" - null value in column "id" of relation "season" violates not-null constraint
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```
already updated to the latest docker image.
This happens with shows added via GUI or API, and multiple shows
regards
Faba

**Comment by bonukai** [comment]
This was only affecting PostgreSQL, should be fixed now

**Comment by Fabaderheld** [comment]
Great I'll test it when I get home !

**Comment by Fabaderheld** [comment]
Works! Thanks!
