### ISSUE TITLE
TV item not loading

### ISSUE THREAD

**Issue by Quentin-ctrL** [bonukai/MediaTracker#453]
Hi,

When opening "Fear the Walking Dead" I only get "Loading"
This happened few days ago. 
I use French for TMDB language

logs:
```
...
25/12/2022 13:48:39 error: TypeError: Cannot read properties of undefined (reading 'map')
    at flatMap (/app/src/updateMetadata.ts:330:29)
    at Array.flatMap (<anonymous>)
    at updateMediaItem (/app/src/updateMetadata.ts:329:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Array.<anonymous> (/app/src/controllers/item.ts:34:7)
...
25/12/2022 13:53:01 info: Updating: Fear the Walking Dead (last updated at: 11/30/2022, 7:11:45 PM)
...
```

**Comment by Wyrrrd** [comment]
This seems to be an issue with seasons without episodes.

I had the same error with SPY x FAMILY S02 and the Rings of Power S02 (both not released). Removed the empty seasons from the database manually, now I can access them in the WebUI as usual.

**Comment by bonukai** [comment]
This issue has been fixed in `mediatracker:unstable` version
