### ISSUE TITLE
 500: Server error  SqliteError: ROLLBACK - cannot rollback - no transaction is active

### ISSUE THREAD

**Issue by averageguyoriginal** [bonukai/MediaTracker#550]
hi. my disk was full where i store mediatracker files. i didnt know and pulled the latest update through docker compose. and now it give this error when i try to access it.

> 500: Server error
> SqliteError: ROLLBACK - cannot rollback - no transaction is active

the logs shows these:

`$ docker logs mediatracker 

PUID: 1000
PGID: 1000

info:  Creating config directory at /home/abc/.mediatracker
Can't take lock to run migrations: update `knex_migrations_lock` set `is_locked` = 1 where `is_locked` = 0 - database or disk is full
If you are sure migrations are not running you can release the lock manually by running 'knex migrate:unlock'
SqliteError: ROLLBACK - cannot rollback - no transaction is active
    at Client_BetterSQLite3._query (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:38)
    at executeQuery (/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (/app/node_modules/knex/lib/client.js:146:12)
    at /app/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_BetterSQLite3.trxClient.query (/app/node_modules/knex/lib/execution/transaction.js:358:12)
    at Transaction_Sqlite.query (/app/node_modules/knex/lib/execution/transaction.js:159:8)
    at Transaction_Sqlite.rollback (/app/node_modules/knex/lib/execution/transaction.js:135:25)
    at Function.transactor.rollback (/app/node_modules/knex/lib/execution/transaction.js:315:42)
    at /app/node_modules/knex/lib/execution/transaction.js:231:35
starting server at http://bc395c4de930:7481
`

i made free space in disk now & restarted the container, even force recreated but getting same error.

before clearing space the container health was "starting"
now it says its healthy but gives the same error.

please guide me how to fix these issue?
thank you

**Comment by averageguyoriginal** [comment]
i restarted the system and run docker again and its working now.
