### ISSUE TITLE
Fails to compile on macOS

### ISSUE THREAD

**Issue by superbonaci** [bonukai/MediaTracker#660]
macOS with Apple M1, [MediaTracker](https://github.com/bonukai/MediaTracker) 2.0.5:

```
$ npm install

> postinstall
> cd server && npm install && cd ../client && npm install

npm error code 1
npm error path /mydrive/MediaTracker_bonukai/server/node_modules/better-sqlite3
npm error command failed
npm error command sh -c prebuild-install || node-gyp rebuild --release
npm error TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm error   ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm error   TOUCH Release/obj.target/deps/locate_sqlite3.stamp
npm error   CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
npm error   LIBTOOL-STATIC Release/sqlite3.a
npm error   CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
npm error rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm error prebuild-install WARN install No prebuilt binaries found (target=23.5.0 runtime=node arch=arm64 libc= platform=darwin)
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@11.0.0
npm error gyp info using node@23.5.0 | darwin | arm64
npm error gyp info find Python using Python version 3.13.1 found at "/opt/homebrew/opt/python@3.13/bin/python3.13"
npm error gyp info spawn /opt/homebrew/opt/python@3.13/bin/python3.13
npm error gyp info spawn args [
npm error gyp info spawn args '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/mydrive/MediaTracker_bonukai/server/node_modules/better-sqlite3/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/memetix_/Library/Caches/node-gyp/23.5.0/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/Users/memetix_/Library/Caches/node-gyp/23.5.0',
npm error gyp info spawn args '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/Users/memetix_/Library/Caches/node-gyp/23.5.0/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/mydrive/MediaTracker_bonukai/server/node_modules/better-sqlite3',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp info spawn make
npm error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm error In file included from ../src/better_sqlite3.cpp:4:
npm error In file included from ./src/better_sqlite3.lzz:11:
npm error In file included from /Users/memetix_/Library/Caches/node-gyp/23.5.0/include/node/node.h:73:
npm error In file included from /Users/memetix_/Library/Caches/node-gyp/23.5.0/include/node/v8.h:23:
npm error In file included from /Users/memetix_/Library/Caches/node-gyp/23.5.0/include/node/cppgc/common.h:8:
npm error /Users/memetix_/Library/Caches/node-gyp/23.5.0/include/node/v8config.h:13:2: error: "C++20 or later required."
npm error    13 | #error "C++20 or later required."
npm error       |  ^
npm error In file included from ../src/better_sqlite3.cpp:4:
npm error ./src/util/macros.lzz:31:69: error: no template named 'CopyablePersistentTraits' in namespace 'v8'; did you mean 'NonCopyablePersistentTraits'?
npm error    31 | template <class T> using CopyablePersistent = v8::Persistent<T, v8::CopyablePersistentTraits<T>>;
npm error       |                                                                 ~~~~^~~~~~~~~~~~~~~~~~~~~~~~
npm error       |                                                                     NonCopyablePersistentTraits
npm error /Users/memetix_/Library/Caches/node-gyp/23.5.0/include/node/v8-persistent-handle.h:223:7: note: 'NonCopyablePersistentTraits' declared here
npm error   223 | class NonCopyablePersistentTraits {
npm error       |       ^
npm error In file included from ../src/better_sqlite3.cpp:4:
npm error ./src/util/macros.lzz:142:142: error: no type named 'AccessorGetterCallback' in namespace 'v8'; did you mean 'AccessorNameGetterCallback'?
npm error   142 | void SetPrototypeGetter (v8::Isolate * isolate, v8::Local <v8::External> data, v8::Local <v8::FunctionTemplate> recv, char const * name, v8::AccessorGetterCallback func);
npm error       |                                                                                                                                          ~~~~^~~~~~~~~~~~~~~~~~~~~~
npm error       |                                                                                                                                              AccessorNameGetterCallback
npm error /Users/memetix_/Library/Caches/node-gyp/23.5.0/include/node/v8-object.h:155:7: note: 'AccessorNameGetterCallback' declared here
npm error   155 | using AccessorNameGetterCallback =
npm error       |       ^
npm error ./src/util/macros.lzz:142:142: error: no type named 'AccessorGetterCallback' in namespace 'v8'; did you mean 'AccessorNameGetterCallback'?
npm error   142 | void SetPrototypeGetter (v8::Isolate * isolate, v8::Local <v8::External> data, v8::Local <v8::FunctionTemplate> recv, char const * name, v8::AccessorGetterCallback func)
npm error       |                                                                                                                                          ~~~~^~~~~~~~~~~~~~~~~~~~~~
npm error       |                                                                                                                                              AccessorNameGetterCallback
npm error /Users/memetix_/Library/Caches/node-gyp/23.5.0/include/node/v8-object.h:155:7: note: 'AccessorNameGetterCallback' declared here
npm error   155 | using AccessorNameGetterCallback =
npm error       |       ^
npm error ./src/util/macros.lzz:150:35: error: no member named 'SetAccessor' in 'v8::ObjectTemplate'
npm error   150 |         recv->InstanceTemplate()->SetAccessor(
npm error       |         ~~~~~~~~~~~~~~~~~~~~~~~~~~^
npm error ./src/objects/database.lzz:17:17: error: no matching function for call to 'SetPrototypeGetter'
npm error    17 |                 SetPrototypeGetter(isolate, data, t, "open", JS_open);
npm error       |                 ^~~~~~~~~~~~~~~~~~
npm error ./src/util/macros.lzz:142:6: note: candidate function not viable: no known conversion from 'void (v8::Local<v8::String>, const v8::PropertyCallbackInfo<v8::Value> &)' to 'v8::AccessorNameGetterCallback' (aka 'void (*)(Local<Name>, const PropertyCallbackInfo<Value> &)') for 5th argument
npm error   142 | void SetPrototypeGetter (v8::Isolate * isolate, v8::Local <v8::External> data, v8::Local <v8::FunctionTemplate> recv, char const * name, v8::AccessorGetterCallback func)
npm error       |      ^                                                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error ./src/objects/database.lzz:18:17: error: no matching function for call to 'SetPrototypeGetter'
npm error    18 |                 SetPrototypeGetter(isolate, data, t, "inTransaction", JS_inTransaction);
npm error       |                 ^~~~~~~~~~~~~~~~~~
npm error ./src/util/macros.lzz:142:6: note: candidate function not viable: no known conversion from 'void (v8::Local<v8::String>, const v8::PropertyCallbackInfo<v8::Value> &)' to 'v8::AccessorNameGetterCallback' (aka 'void (*)(Local<Name>, const PropertyCallbackInfo<Value> &)') for 5th argument
npm error   142 | void SetPrototypeGetter (v8::Isolate * isolate, v8::Local <v8::External> data, v8::Local <v8::FunctionTemplate> recv, char const * name, v8::AccessorGetterCallback func)
npm error       |      ^                                                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error ./src/objects/database.lzz:180:21: warning: variable 'status' set but not used [-Wunused-but-set-variable]
npm error   180 |                 int status = sqlite3_db_config(db_handle, SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION, 1, NULL);
npm error       |                     ^
npm error ./src/objects/statement.lzz:16:17: error: no matching function for call to 'SetPrototypeGetter'
npm error    16 |                 SetPrototypeGetter(isolate, data, t, "busy", JS_busy);
npm error       |                 ^~~~~~~~~~~~~~~~~~
npm error ./src/util/macros.lzz:142:6: note: candidate function not viable: no known conversion from 'void (v8::Local<v8::String>, const v8::PropertyCallbackInfo<v8::Value> &)' to 'v8::AccessorNameGetterCallback' (aka 'void (*)(Local<Name>, const PropertyCallbackInfo<Value> &)') for 5th argument
npm error   142 | void SetPrototypeGetter (v8::Isolate * isolate, v8::Local <v8::External> data, v8::Local <v8::FunctionTemplate> recv, char const * name, v8::AccessorGetterCallback func)
npm error       |      ^                                                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error 1 warning and 8 errors generated.
npm error make: *** [Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 1
npm error gyp ERR! build error
npm error gyp ERR! stack Error: `make` failed with exit code: 2
npm error gyp ERR! stack at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:216:23)
npm error gyp ERR! System Darwin 24.2.0
npm error gyp ERR! command "/opt/homebrew/Cellar/node/23.5.0/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm error gyp ERR! cwd /mydrive/MediaTracker_bonukai/server/node_modules/better-sqlite3
npm error gyp ERR! node -v v23.5.0
npm error gyp ERR! node-gyp -v v11.0.0
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: /Users/memetix_/.npm/_logs/2024-12-26T21_25_18_656Z-debug-0.log
npm error code 1
npm error path /mydrive/MediaTracker_bonukai
npm error command failed
npm error command sh -c cd server && npm install && cd ../client && npm install
npm error A complete log of this run can be found in: /Users/memetix_/.npm/_logs/2024-12-26T21_25_17_482Z-debug-0.log
```

**Comment by bonukai** [comment]
This is an issue with `better-sqlite3`, there are no prebuild binaries for your nodejs version and platform, so it tries to build it from source and it fails the build.

Could you try using LTS version of nodejs?

From https://github.com/WiseLibs/better-sqlite3
> You must be using Node.js v14.21.1 or above. Prebuilt binaries are available for [LTS versions](https://nodejs.org/en/about/releases/). If you have trouble installing, check the [troubleshooting guide](https://github.com/WiseLibs/better-sqlite3/blob/master/docs/troubleshooting.md).

**Comment by superbonaci** [comment]
Doesn't work:

```
$ npm install

> postinstall
> cd server && npm install && cd ../client && npm install

npm error code 1
npm error path /mydrive/MediaTracker_bonukai/server/node_modules/better-sqlite3
npm error command failed
npm error command sh -c prebuild-install || node-gyp rebuild --release
npm error TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm error   ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm error   TOUCH Release/obj.target/deps/locate_sqlite3.stamp
npm error   CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
npm error   LIBTOOL-STATIC Release/sqlite3.a
npm error   CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
npm error rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm error prebuild-install WARN install No prebuilt binaries found (target=22.12.0 runtime=node arch=arm64 libc= platform=darwin)
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.2.0
npm error gyp info using node@22.12.0 | darwin | arm64
npm error gyp info find Python using Python version 3.13.1 found at "/opt/homebrew/opt/python@3.13/bin/python3.13"
npm error gyp info spawn /opt/homebrew/opt/python@3.13/bin/python3.13
npm error gyp info spawn args [
npm error gyp info spawn args '/opt/homebrew/Cellar/node@22/22.12.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/mydrive/MediaTracker_bonukai/server/node_modules/better-sqlite3/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/opt/homebrew/Cellar/node@22/22.12.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/memetix_/Library/Caches/node-gyp/22.12.0/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/Users/memetix_/Library/Caches/node-gyp/22.12.0',
npm error gyp info spawn args '-Dnode_gyp_dir=/opt/homebrew/Cellar/node@22/22.12.0/lib/node_modules/npm/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/Users/memetix_/Library/Caches/node-gyp/22.12.0/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/mydrive/MediaTracker_bonukai/server/node_modules/better-sqlite3',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp info spawn make
npm error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm error ./src/util/macros.lzz:150:35: error: no matching member function for call to 'SetAccessor'
npm error   150 |         recv->InstanceTemplate()->SetAccessor(
npm error       |         ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
npm error /Users/memetix_/Library/Caches/node-gyp/22.12.0/include/node/v8-template.h:1049:8: note: candidate function not viable: no known conversion from 'v8::AccessControl' to 'PropertyAttribute' for 5th argument
npm error  1049 |   void SetAccessor(
npm error       |        ^
npm error  1050 |       Local<String> name, AccessorGetterCallback getter,
npm error  1051 |       AccessorSetterCallback setter = nullptr,
npm error  1052 |       Local<Value> data = Local<Value>(), PropertyAttribute attribute = None,
npm error       |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /Users/memetix_/Library/Caches/node-gyp/22.12.0/include/node/v8-template.h:1055:8: note: candidate function not viable: no known conversion from 'v8::AccessorGetterCallback' (aka 'void (*)(Local<String>, const PropertyCallbackInfo<Value> &)') to 'AccessorNameGetterCallback' (aka 'void (*)(Local<Name>, const PropertyCallbackInfo<Value> &)') for 2nd argument
npm error  1055 |   void SetAccessor(
npm error       |        ^
npm error  1056 |       Local<Name> name, AccessorNameGetterCallback getter,
npm error       |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error ./src/objects/database.lzz:180:21: warning: variable 'status' set but not used [-Wunused-but-set-variable]
npm error   180 |                 int status = sqlite3_db_config(db_handle, SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION, 1, NULL);
npm error       |                     ^
npm error 1 warning and 1 error generated.
npm error make: *** [Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 1
npm error gyp ERR! build error
npm error gyp ERR! stack Error: `make` failed with exit code: 2
npm error gyp ERR! stack at ChildProcess.<anonymous> (/opt/homebrew/Cellar/node@22/22.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:216:23)
npm error gyp ERR! System Darwin 24.2.0
npm error gyp ERR! command "/opt/homebrew/Cellar/node@22/22.12.0/bin/node" "/opt/homebrew/Cellar/node@22/22.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm error gyp ERR! cwd /mydrive/MediaTracker_bonukai/server/node_modules/better-sqlite3
npm error gyp ERR! node -v v22.12.0
npm error gyp ERR! node-gyp -v v10.2.0
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: /Users/memetix_/.npm/_logs/2024-12-27T10_43_25_516Z-debug-0.log
npm error code 1
npm error path /mydrive/MediaTracker_bonukai
npm error command failed
npm error command sh -c cd server && npm install && cd ../client && npm install
npm error A complete log of this run can be found in: /Users/memetix_/.npm/_logs/2024-12-27T10_43_24_876Z-debug-0.log
```

**Comment by superbonaci** [comment]
It happens also on Linux with node v23.4.0. I can't switch to LTS because then can't test software and report bugs.

**Comment by bonukai** [comment]
`better-sqlite3` has been updated to `11.7.0` on the `main` branch, this should resolve this issue.

**Comment by superbonaci** [comment]
Yes now it's fixed and works with latest node. Thanks.
