### ISSUE TITLE
trakt.tv import errors

### ISSUE THREAD

**Issue by clach04** [bonukai/MediaTracker#67]
This is not something I need but I was experimenting with trakt.tv, initial setup was very straight forward, great UI/design 👍 .

The list to import looked much smaller than than what I see in https://trakt.tv/users/clach04/history/episodes/ (missing titles) - I did the import anyway, and that appeared to work but:

* seen history missing on a number of episodes
* no ratings imported

I see an error in the Docker log:

    C:\docker\mediatracker>docker image ls
    REPOSITORY             TAG       IMAGE ID       CREATED        SIZE
    bonukai/mediatracker   latest    70726fc8bd32   14 hours ago   230MB

    C:\docker\mediatracker>docker logs mediatracker
    Running migrations
    Already up to date
    MediaTracker listening at http://-----------:7481
    Updating metadata
    Everything up to date
    TypeError: Cannot read properties of undefined (reading 'id')
        at /app/build/controllers/traktTvImport.js:181:227
        at Array.map (<anonymous>)
        at Array.<anonymous> (/app/build/controllers/traktTvImport.js:176:146)

I don't need this but if I can provide diagnostics let me know.

**Comment by bayang** [comment]
Hi ! 

Same issue here with 0.0.8, trakt import imports only the watch list but not the history (I don't have any ratings).

If I stay on the import page I can see a partial import status (see screenshot) and hundreds of request to the state endoint, giving the same json response  : 
```
"{\"state\":\"importing\",\"exportSummary\":{\"watchlist\":{\"movies\":21,\"shows\":41},\"seen\":{\"movies\":0,\"episodes\":10},\"ratings\":{\"movies\":0,\"shows\":0,\"seasons\":0,\"episodes\":0}}}"
```

![mediatracker](https://user-images.githubusercontent.com/11558944/167837120-4aded62d-c49c-49e7-970c-3d6b783b659a.jpg)

There is much more data than this on my trakt account.

The watchlist numbers are good, but not the rest.

After several hours, nothing has changed, I tried to launch a new import with same result.

**Comment by DragonHeart69** [comment]
Hey,

Installed today for the first time. Looks much better/easier/workable than flox. However, I notice that nothing from trakt is imported (see screenshot). This while there are more than 3000 episodes. In the docker logs nothing appears.

![2022-08-20 18_39_06-Media Tracker - Brave](https://user-images.githubusercontent.com/21025274/185757680-d023621d-e4a9-410e-95b8-1f26fb9ab18d.png)
