### ISSUE TITLE
South Park (only first 13 seasons show up)

### ISSUE THREAD

**Issue by gabeanelson** [bonukai/MediaTracker#68]
South Park just started season 25, but only the first 13 seasons show up.

**Comment by bonukai** [comment]
Could you share docker logs?
```bash
docker logs MediaTracker
```

**Comment by gabeanelson** [comment]
Below is the docker logs. I'm not getting any errors. Could it be the data source of the information that goes into the Media Tracker? 

Running migrations
Already up to date
MediaTracker listening at http://c012fc8367d1:7481
Updating metadata
Everything up to date
Running migrations
Already up to date
MediaTracker listening at http://c012fc8367d1:7481
Updating metadata
Everything up to date
Running migrations
Already up to date
MediaTracker listening at http://c012fc8367d1:7481
Updating metadata
Everything up to date
Running migrations
Already up to date
MediaTracker listening at http://c012fc8367d1:7481
Updating metadata
Everything up to date
Running migrations
Already up to date
MediaTracker listening at http://c012fc8367d1:7481
Updating metadata
Everything up to date

Below I've included some screen shots to show what I'm seeing in Media Tracker. Also for comparison, I show South Park's list of seasons that I found on Wikipedia (for comparison).
![Media Tracker - South Park](https://user-images.githubusercontent.com/34947513/152554447-49f79ebd-5f0e-455a-9dd1-813756a6909b.png)
![Wikipedia - South Park](https://user-images.githubusercontent.com/34947513/152554473-66fe0d4a-9d42-4ef5-8293-56e1aec618a6.png)

**Comment by bonukai** [comment]
That is very strange. TV shows data is pulled from TMBD and they do have all seasons.

Could you search for "South park" in MediaTracker and see if there is more then one result?

Active TV shows should update every 24 hours, so hopefully it will fix itself soon.

**Comment by SirBogner** [comment]
For me all 25 seasons show up. Number of episodes in each seems to match. Although my instance can't load "The Book of Boba Fett". I keep getting "server error 500".

**Comment by bonukai** [comment]
I just added `Update metadata` button in the details page. Can you try to use it, and if it still wont work, could you paste logs from the settings page [http://localhost:7481/#/settings/logs](http://localhost:7481/#/settings/logs) or from Docker

**Comment by SirBogner** [comment]
Neat. The new update didn't change my ability to access the Book of Boba Fett page.

My logs:

25.2.2022 09.20.13error: SqliteError: delete from `episode` where `id` in (399) - FOREIGN KEY constraint failed
    at Client_BetterSQLite3._query (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:38)
    at executeQuery (/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (/app/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/app/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:307:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async updateMediaItem (/app/build/updateMetadata.js:273:9)
25.2.2022 09.20.12info: Updating: The Book of Boba Fett (last updated at: 2/15/2022, 2:01:44 PM)
25.2.2022 09.20.09error: SqliteError: delete from `episode` where `id` in (399) - FOREIGN KEY constraint failed
    at Client_BetterSQLite3._query (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:38)
    at executeQuery (/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (/app/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/app/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:307:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async updateMediaItem (/app/build/updateMetadata.js:273:9)
25.2.2022 09.20.08info: Updating: The Book of Boba Fett (last updated at: 2/15/2022, 2:01:44 PM)
25.2.2022 09.20.06error: SqliteError: delete from `episode` where `id` in (399) - FOREIGN KEY constraint failed
    at Client_BetterSQLite3._query (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:38)
    at executeQuery (/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (/app/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/app/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:307:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async updateMediaItem (/app/build/updateMetadata.js:273:9)
25.2.2022 09.20.04info: Updating: The Book of Boba Fett (last updated at: 2/15/2022, 2:01:44 PM)

**Comment by gabeanelson** [comment]
With the most recent update, I'm not having the same issue I was having. I can see all of the episodes for South Park. Thanks for the update!! This is such a great product!

**Comment by bonukai** [comment]
> Neat. The new update didn't change my ability to access the Book of Boba Fett page.
> 
> My logs:
> 
> ```
> 25.2.2022 09.20.13error: SqliteError: delete from `episode` where `id` in (399) - FOREIGN KEY constraint failed
>     at Client_BetterSQLite3._query (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:38)
>     at executeQuery (/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
>     at Client_BetterSQLite3.query (/app/node_modules/knex/lib/client.js:146:12)
>     at Runner.query (/app/node_modules/knex/lib/execution/runner.js:130:36)
>     at ensureConnectionCallback (/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
>     at Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:307:20)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
>     at async updateMediaItem (/app/build/updateMetadata.js:273:9)
> 25.2.2022 09.20.12info: Updating: The Book of Boba Fett (last updated at: 2/15/2022, 2:01:44 PM)
> 25.2.2022 09.20.09error: SqliteError: delete from `episode` where `id` in (399) - FOREIGN KEY constraint failed
>     at Client_BetterSQLite3._query (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:38)
>     at executeQuery (/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
>     at Client_BetterSQLite3.query (/app/node_modules/knex/lib/client.js:146:12)
>     at Runner.query (/app/node_modules/knex/lib/execution/runner.js:130:36)
>     at ensureConnectionCallback (/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
>     at Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:307:20)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
>     at async updateMediaItem (/app/build/updateMetadata.js:273:9)
> 25.2.2022 09.20.08info: Updating: The Book of Boba Fett (last updated at: 2/15/2022, 2:01:44 PM)
> 25.2.2022 09.20.06error: SqliteError: delete from `episode` where `id` in (399) - FOREIGN KEY constraint failed
>     at Client_BetterSQLite3._query (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:38)
>     at executeQuery (/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
>     at Client_BetterSQLite3.query (/app/node_modules/knex/lib/client.js:146:12)
>     at Runner.query (/app/node_modules/knex/lib/execution/runner.js:130:36)
>     at ensureConnectionCallback (/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
>     at Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:307:20)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
>     at async updateMediaItem (/app/build/updateMetadata.js:273:9)
> 25.2.2022 09.20.04info: Updating: The Book of Boba Fett (last updated at: 2/15/2022, 2:01:44 PM)
> ```

I was hoping this would never happen, it's quite difficult problem to solve.

An episode, that you've marked as seen, or rated, has been removed from the TMDB. Unfortunately this happens from time to time. Sometimes two last episodes of a season (Part 1, Part 2), are joined together, into one. When first episode of Dexter: New Blood aired, it was listed as season 9 of Dexter, but soon it was removed.

So the real question is: what to do with those deleted episodes marked as seen, or rated?

Easiest solution would be to just delete it with all those seen records and ratings, but I don't thing that would be a good user experience. No user data should be deleted without explicit user action.

I think I will marked those deleted episodes in a database as deleted, but won't really remove them (it's called soft delete), and we could display on top of the page list of all those deleted episodes for every deleted episode.

For example: "an episode of Book of Boba Feet S01E08, but you marked it as seen"

**Comment by SirBogner** [comment]
That does make a lot of sense. Thanks for clarifying. 

I quite like the idea of soft deleting and make the end user able to take action or at least be informed about issues.
